version: "3.8"

services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: signa
      POSTGRES_PASSWORD: signa_pass
      POSTGRES_DB: signa_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://signa:signa_pass@db/signa_db
    depends_on:
      - db

volumes:
  postgres_data:
